# Generated by Django 5.2.9 on 2025-12-31 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_employee_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], db_index=True, default='MEMBER', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPermissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], db_index=True, default='ALLOW', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('COMPANY', 'Company'), ('PROJECT', 'Project')], db_index=True, max_length=10)),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('module', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PermissionAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('COMPANY', 'Company'), ('PROJECT', 'Project')], db_index=True, max_length=10)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('OWNER', 'Owner'), ('PARTICIPANT', 'Participant')], db_index=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPermissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], db_index=True, default='ALLOW', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('ALLOW', 'Allow'), ('DENY', 'Deny')], db_index=True, default='ALLOW', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='attached_to_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.company'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['email'], name='idx_client_email'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.company'),
        ),
        migrations.AddField(
            model_name='companymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companypermissionassignment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_assignments', to='core.company'),
        ),
        migrations.AddField(
            model_name='companypermissionassignment',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_company_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companypermissionassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_permission_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['scope', 'code'], name='idx_permission_scope_code'),
        ),
        migrations.AddConstraint(
            model_name='permission',
            constraint=models.UniqueConstraint(fields=('scope', 'code'), name='uniq_permission_scope_code'),
        ),
        migrations.AddField(
            model_name='companypermissionassignment',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_permission_assignments', to='core.permission'),
        ),
        migrations.AddField(
            model_name='permissionauditevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='permissionauditevent',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_audit_events', to='core.company'),
        ),
        migrations.AddField(
            model_name='permissionauditevent',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_audit_events', to='core.project'),
        ),
        migrations.AddField(
            model_name='permissionauditevent',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcompany',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='core.company'),
        ),
        migrations.AddField(
            model_name='projectcompany',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_company_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcompany',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='core.project'),
        ),
        migrations.AddField(
            model_name='projectpermissionassignment',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_project_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectpermissionassignment',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_permission_assignments', to='core.permission'),
        ),
        migrations.AddField(
            model_name='projectpermissionassignment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_assignments', to='core.project'),
        ),
        migrations.AddField(
            model_name='projectpermissionassignment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_permission_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectrole',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roles', to='core.company'),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.projectrole'),
        ),
        migrations.AddIndex(
            model_name='projectuser',
            index=models.Index(fields=['project', 'user'], name='idx_projectuser_project_user'),
        ),
        migrations.AddIndex(
            model_name='projectuser',
            index=models.Index(fields=['user', 'project'], name='idx_projectuser_user_project'),
        ),
        migrations.AddField(
            model_name='projectrolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_role_permissions', to='core.permission'),
        ),
        migrations.AddField(
            model_name='projectrolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.projectrole'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['company', 'user'], name='idx_membership_company_user'),
        ),
        migrations.AddIndex(
            model_name='companymembership',
            index=models.Index(fields=['user', 'company'], name='idx_membership_user_company'),
        ),
        migrations.AddConstraint(
            model_name='companymembership',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='uniq_membership_user_company'),
        ),
        migrations.AddIndex(
            model_name='companypermissionassignment',
            index=models.Index(fields=['company', 'user'], name='idx_companyperm_company_user'),
        ),
        migrations.AddIndex(
            model_name='companypermissionassignment',
            index=models.Index(fields=['user', 'company'], name='idx_companyperm_user_company'),
        ),
        migrations.AddIndex(
            model_name='companypermissionassignment',
            index=models.Index(fields=['permission', 'effect'], name='idx_cperm_perm_eff'),
        ),
        migrations.AddConstraint(
            model_name='companypermissionassignment',
            constraint=models.UniqueConstraint(fields=('company', 'user', 'permission'), name='uniq_company_user_permission'),
        ),
        migrations.AddConstraint(
            model_name='companypermissionassignment',
            constraint=models.CheckConstraint(condition=models.Q(('effect__in', ['ALLOW', 'DENY'])), name='chk_companyperm_effect'),
        ),
        migrations.AddIndex(
            model_name='permissionauditevent',
            index=models.Index(fields=['scope', 'created_at'], name='idx_permaudit_scope_created'),
        ),
        migrations.AddIndex(
            model_name='permissionauditevent',
            index=models.Index(fields=['target_user', 'created_at'], name='idx_permaudit_target_created'),
        ),
        migrations.AddIndex(
            model_name='projectcompany',
            index=models.Index(fields=['company', 'project'], name='idx_prjco_co_prj'),
        ),
        migrations.AddConstraint(
            model_name='projectcompany',
            constraint=models.UniqueConstraint(fields=('project', 'company'), name='uniq_project_company'),
        ),
        migrations.AddConstraint(
            model_name='projectcompany',
            constraint=models.CheckConstraint(condition=models.Q(('relationship__in', ['OWNER', 'PARTICIPANT'])), name='chk_project_company_relationship'),
        ),
        migrations.AddIndex(
            model_name='projectpermissionassignment',
            index=models.Index(fields=['project', 'user'], name='idx_projectperm_project_user'),
        ),
        migrations.AddIndex(
            model_name='projectpermissionassignment',
            index=models.Index(fields=['user', 'project'], name='idx_projectperm_user_project'),
        ),
        migrations.AddIndex(
            model_name='projectpermissionassignment',
            index=models.Index(fields=['permission', 'effect'], name='idx_pperm_perm_eff'),
        ),
        migrations.AddConstraint(
            model_name='projectpermissionassignment',
            constraint=models.UniqueConstraint(fields=('project', 'user', 'permission'), name='uniq_project_user_permission'),
        ),
        migrations.AddConstraint(
            model_name='projectpermissionassignment',
            constraint=models.CheckConstraint(condition=models.Q(('effect__in', ['ALLOW', 'DENY'])), name='chk_projectperm_effect'),
        ),
        migrations.AddIndex(
            model_name='projectrole',
            index=models.Index(fields=['company', 'name'], name='idx_projectrole_company_name'),
        ),
        migrations.AddConstraint(
            model_name='projectrole',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_projectrole_company_name'),
        ),
        migrations.AddIndex(
            model_name='projectrolepermission',
            index=models.Index(fields=['permission', 'effect'], name='idx_prjrole_perm_eff'),
        ),
        migrations.AddConstraint(
            model_name='projectrolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uniq_projectrole_permission'),
        ),
        migrations.AddConstraint(
            model_name='projectrolepermission',
            constraint=models.CheckConstraint(condition=models.Q(('effect__in', ['ALLOW', 'DENY'])), name='chk_projectroleperm_effect'),
        ),
    ]
